# This file was generated by GoReleaser. DO NOT EDIT.
cask "qdf-hook" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d82901fb1994172017844791b607747a61efcefdedc36f4a300b842a0b5c239b"
      url "https://github.com/alex60217101990/terse/releases/download/v#{version}/terse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b9dbd9be6a5f08ae0055ac34faa2922189eb0a7ed0416aa030ecd010f45e3a3"
      url "https://github.com/alex60217101990/terse/releases/download/v#{version}/terse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "54a22c78e6883f6b88decd6cd5452b63717f868dc79406239eea970da268dbc0"
      url "https://github.com/alex60217101990/terse/releases/download/v#{version}/terse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "192e1945f9346004b0fc30c15f61796fc5d80bab8ce8586939b6601278203a25"
      url "https://github.com/alex60217101990/terse/releases/download/v#{version}/terse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qdf-hook"
  desc "Claude Code token-saving hooks + resident daemon"
  homepage "https://github.com/alex60217101990/terse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qdf-hook"

  postflight do
    client = Dir["#{staged_path}/qdf-hookc/qdf-hookc-*"].first
    if client
      FileUtils.chmod 0755, client
      bin = "#{HOMEBREW_PREFIX}/bin/qdf-hookc"
      FileUtils.cp client, bin
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Wire qdf-hook into Claude Code, then restart it:
      qdf-hook init
    The resident daemon starts itself at SessionStart; upgrades replace it.
  EOS
end
