# This file was generated by GoReleaser. DO NOT EDIT.
cask "qdf-hook" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "e1635c84eb2d52980125ed8f1d4c573a5ef21ab272909dafed8a7bb0eb9de6f0"
      url "https://github.com/alex60217101990/terse/releases/download/v#{version}/terse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dddde8c563e74c653178cec100a3f32abd5bba1c58f676170487e272eb44361c"
      url "https://github.com/alex60217101990/terse/releases/download/v#{version}/terse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b205f78c2f407354b9aa2dfd8ff294a968a6f2d2bcbf43200e4c56f163322877"
      url "https://github.com/alex60217101990/terse/releases/download/v#{version}/terse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f557c29306a018bc6c4d0b40dfc374f06e733a8b849d48ea666b7d38378700a0"
      url "https://github.com/alex60217101990/terse/releases/download/v#{version}/terse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qdf-hook"
  desc "Claude Code token-saving hooks + resident daemon"
  homepage "https://github.com/alex60217101990/terse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qdf-hook"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", staged_path],
                   must_succeed: false
    client = Dir["#{staged_path}/qdf-hookc/qdf-hookc-*"].first
    if client
      bin = "#{HOMEBREW_PREFIX}/bin/qdf-hookc"
      FileUtils.cp client, bin
      FileUtils.chmod 0755, bin
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", bin],
                     must_succeed: false
    end
  end

  uninstall_postflight do
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/bin/qdf-hookc"
  end

  # No zap stanza required

  caveats <<~EOS
    Wire qdf-hook into Claude Code, then restart it:
      qdf-hook init
    The resident daemon starts itself at SessionStart; upgrades replace it.
  EOS
end
