# This file was generated by GoReleaser. DO NOT EDIT.
cask "qdf-hook" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "a0f549c4e72b8d1726ed65affc5704c61e22fec8c1df2e334b1bdcb8549f0092"
      url "https://github.com/alex60217101990/terse/releases/download/v#{version}/terse_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa31dc76af4cb0fc4f8f3c91de773cbf8b2d554b8a65a844e465407811d60129"
      url "https://github.com/alex60217101990/terse/releases/download/v#{version}/terse_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8e03dfb24bb4345d3099bd268d699c7772567f8c446c8f4384a949935c50202b"
      url "https://github.com/alex60217101990/terse/releases/download/v#{version}/terse_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b3c1e1df6c88f1b750c818aa5ee00054604da576c84cd4c48d842648314d8fd4"
      url "https://github.com/alex60217101990/terse/releases/download/v#{version}/terse_#{version}_linux_arm64.tar.gz"
    end
  end

  name "qdf-hook"
  desc "Claude Code token-saving hooks + resident daemon"
  homepage "https://github.com/alex60217101990/terse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qdf-hook"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", staged_path],
                   must_succeed: false
    client = Dir["#{staged_path}/qdf-hookc/qdf-hookc-*"].first
    if client
      bin = "#{HOMEBREW_PREFIX}/bin/qdf-hookc"
      FileUtils.cp client, bin
      FileUtils.chmod 0755, bin
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", bin],
                     must_succeed: false
    end
  end

  uninstall_postflight do
    FileUtils.rm_f "#{HOMEBREW_PREFIX}/bin/qdf-hookc"
  end

  # No zap stanza required

  caveats <<~EOS
    Wire qdf-hook into Claude Code, then restart it:
      qdf-hook init
    The resident daemon starts itself at SessionStart; upgrades replace it.
  EOS
end
